name: Hellp program

on:
 push:
 
jobs:
  say-hey:
    runs-on: ubuntu-latest
    steps:
      - name: checkout process
        uses: actions/checkout@v4

      - name: print hello
        run: echo"hello world"
    

  
  



